---
permalink: sg6000/replacing-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, Replacing, replace, sg6000-cn, controller, remove, removing, removal, install, installing, installation 
summary: Potrebbe essere necessario sostituire il controller SG6000-CN se non funziona in modo ottimale o se si è verificato un guasto. 
---
= Sostituire il controller SG6000-CN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario sostituire il controller SG6000-CN se non funziona in modo ottimale o se si è verificato un guasto.

.Prima di iniziare
* Si dispone di un controller sostitutivo con lo stesso numero di parte del controller che si sta sostituendo.
* Sono presenti etichette per identificare ciascun cavo collegato al controller.
* Il controller da sostituire nel data center è stato fisicamente posizionato.
+
link:locating-controller-in-data-center.html["Individuare il controller nel data center"]



.A proposito di questa attività
Il nodo di storage dell'appliance non sarà accessibile quando si sostituisce il controller SG6000-CN. Se il controller SG6000-CN funziona a sufficienza, è possibile eseguire un arresto controllato all'inizio di questa procedura.


NOTE: Se si sostituisce il controller prima di installare il software StorageGRID, potrebbe non essere possibile accedere al programma di installazione dell'appliance StorageGRID subito dopo aver completato questa procedura. Sebbene sia possibile accedere al programma di installazione dell'appliance StorageGRID da altri host sulla stessa sottorete dell'appliance, non è possibile accedervi da host su altre subnet. Questa condizione dovrebbe risolversi entro 15 minuti (quando qualsiasi voce della cache ARP per il timeout del controller originale), oppure è possibile cancellare immediatamente la condizione cancellando manualmente le vecchie voci della cache ARP dal router o gateway locale.

.Fasi
. Visualizzare le configurazioni correnti dell'appliance e registrarle.
+
.. Accedere all'apparecchio da sostituire:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



.. Inserire: `*run-host-command ipmitool lan print*` Per visualizzare le configurazioni BMC correnti per l'appliance.


. Se il controller SG6000-CN funziona in modo sufficiente per consentire un arresto controllato, spegnere il controller SG6000-CN.
+
link:shutting-down-sg6000-cn-controller.html["Spegnere il controller SG6000-CN"]

. Se una delle interfacce di rete di questo dispositivo StorageGRID è configurata per DHCP, potrebbe essere necessario aggiornare le assegnazioni permanenti del lease DHCP sui server DHCP per fare riferimento agli indirizzi MAC del dispositivo sostitutivo. L'aggiornamento garantisce che all'appliance siano assegnati gli indirizzi IP previsti. Vedere link:../commonhardware/locate-mac-address.html["Aggiornare i riferimenti degli indirizzi MAC"].
. Rimuovere e sostituire il controller SG6000-CN:
+
.. Etichettare i cavi, quindi scollegarli e tutti i ricetrasmettitori SFP+ o SFP28.
+

IMPORTANT: Per evitare prestazioni degradate, non attorcigliare, piegare, pizzicare o salire sui cavi.

.. Rimuovere il controller guasto dal cabinet o dal rack.
.. Installare il controller sostitutivo nel cabinet o nel rack.
.. Sostituire i cavi e i ricetrasmettitori SFP+ o SFP28.
.. Accendere il controller e monitorare i LED del controller e i codici di avvio.


. Se l'appliance in cui è stato sostituito il controller utilizzava un server di gestione delle chiavi (KMS) per crittografare i dati, potrebbe essere necessaria una configurazione aggiuntiva prima che il nodo possa unirsi alla griglia. Se il nodo non si unisce automaticamente alla griglia, assicurarsi che queste impostazioni di configurazione siano state trasferite al nuovo controller e configurare manualmente le impostazioni che non hanno la configurazione prevista:
+
** link:../installconfig/configuring-network-links.html["Configurare i collegamenti di rete"]
** link:../installconfig/setting-ip-configuration.html["Configurare gli indirizzi IP StorageGRID"]
** link:../admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["Configurare la crittografia dei nodi per l'appliance"]


. Accedere all'appliance con il controller sostituito:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


. Ripristinare la connettività di rete BMC per l'appliance. Sono disponibili due opzioni:
+
** Utilizzare IP statico, netmask e gateway
** Utilizzare DHCP per ottenere un IP, una netmask e un gateway
+
... Per ripristinare la configurazione BMC in modo che utilizzi un IP statico, una netmask e un gateway, immettere i seguenti comandi:
+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... Per ripristinare la configurazione BMC in modo che utilizzi DHCP per ottenere un IP, una netmask e un gateway, immettere il seguente comando:
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. Dopo aver ripristinato la connettività di rete BMC, connettersi all'interfaccia BMC per controllare e ripristinare eventuali configurazioni BMC personalizzate aggiuntive applicate. Ad esempio, è necessario confermare le impostazioni per le destinazioni dei messaggi trap SNMP e le notifiche e-mail. Vedere link:../installconfig/configuring-bmc-interface.html["Configurare l'interfaccia BMC"].
. Verificare che il nodo appliance sia visualizzato in Grid Manager e che non vengano visualizzati avvisi.


Dopo aver sostituito il componente, restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"^] per ulteriori informazioni.

.Informazioni correlate
link:../installconfig/sg6000-cn-installing-into-cabinet-or-rack.html["Installare SG6000-CN nell'armadio o nel rack"]

link:../installconfig/viewing-status-indicators.html["Visualizzare gli indicatori di stato"]

link:../installconfig/viewing-boot-up-codes-for-sg6000-cn-controller.html["Visualizza i codici di avvio per il controller SG6000-CN"]
