---
settings:
  name: StorageGRID 11.7
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.7 documenti
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes/index.html"
  - title: Inizia subito
    entries:
    - section: primer
    - section: network
    - title: Avvio rapido per StorageGRID
      url: "/primer/quick-start.html"
  - title: Installazione e aggiornamento
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Configurare e gestire
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: USA StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitorare e risolvere i problemi
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Mantenere
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Abilitare StorageGRID
    url: "/storagegrid-enable.html"
  - title: Altre versioni
    url: "/earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: "/release-notes/index.html"
    - title: Novità
      url: "/upgrade/whats-new.html"
    - title: Scopri di più su StorageGRID
      url: "/primer/index.html"
    - title: Linee guida per il networking
      url: "/network/index.html"
    - title: Avvio rapido di StorageGRID
      url: "/primer/quick-start.html"
  - title: Installazione e manutenzione dell'hardware
    links:
    - title: Installare e implementare le appliance
      url: "/installconfig/index.html"
    - title: Manutenzione delle appliance
      url: "/maintain/index.html"
  - title: Installare e aggiornare il software
    links:
    - title: Installare Red Hat Enterprise Linux o CentOS
      url: "/rhel/index.html"
    - title: Installare Ubuntu o Debian
      url: "/ubuntu/index.html"
    - title: Installare VMware
      url: "/vmware/index.html"
    - title: Aggiornare il software
      url: "/upgrade/index.html"
  - title: Configurare la griglia
    links:
    - title: Amministrare StorageGRID
      url: "/admin/index.html"
    - title: Gestire gli oggetti con ILM
      url: "/ilm/index.html"
    - title: Protezione avanzata del sistema
      url: "/harden/index.html"
    - title: Configurare StorageGRID per FabricPool
      url: "/fabricpool/index.html"
  - title: Gestire gli oggetti
    links:
    - title: Utilizzare un account tenant
      url: "/tenant/index.html"
    - title: UTILIZZARE L'API REST S3
      url: "/s3/index.html"
    - title: USA API REST di Swift (obsoleto)
      url: "/swift/index.html"
  - title: Monitoraggio e manutenzione
    links:
    - title: Monitorare
      url: "/monitor/index.html"
    - title: Risolvere i problemi
      url: "/troubleshoot/index.html"
    - title: Esaminare i registri di audit
      url: "/audit/index.html"
    - title: Espandi il tuo grid
      url: "/expand/index.html"
    - title: Ripristino e manutenzione
      url: "/maintain/index.html"
  - title: Demo e tutorial
    links:
    - title: Scopri come attivare StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: Videoteca StorageGRID
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: Servizi di apprendimento NetApp
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Più risorse
    links:
    - title: Pagina di supporto di StorageGRID
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: Tool di matrice di interoperabilità NetApp (IMT)
      url: https://imt.netapp.com/matrix/#welcome
    - title: Knowledge base di StorageGRID
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: Blog di NetApp
      url: https://netapp.com/blog/
    - title: Community di NetApp
      url: https://community.netapp.com/
  - title: Altre versioni
    links:
    - title: Documentazione di StorageGRID 11.6
      url: https://docs.netapp.com/us-en/storagegrid-116/index.html
    - title: Documentazione di StorageGRID 11.5
      url: https://docs.netapp.com/us-en/storagegrid-115/index.html
    - title: Documentazione di StorageGRID 11.4
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: Documentazione di StorageGRID 11.3
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: Documentazione di StorageGRID 11.2
      url: https://docs.netapp.com/sgws-112/index.jsp
