---
settings:
  name: StorageGRID 11.7
  search: storagegrid-enable,storagegrid-117
  downlevel: true
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.7 documenti
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes/index.html"
  - title: Inizia subito
    entries:
    - section: primer
    - section: network
    - title: Avvio rapido per StorageGRID
      url: "/primer/quick-start.html"
  - title: Installazione e aggiornamento
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Configurare e gestire
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: USA StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Monitorare e risolvere i problemi
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Mantenere
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Abilitare StorageGRID
    url: "/storagegrid-enable.html"
  - title: Altre versioni
    url: "/earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
