---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 'È necessario comprendere in che modo il sistema StorageGRID verrà influenzato durante l"aggiornamento.' 
---
= Impatto del sistema durante l'aggiornamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario comprendere in che modo il sistema StorageGRID verrà influenzato durante l'aggiornamento.



== Gli aggiornamenti di StorageGRID sono senza interruzioni

Il sistema StorageGRID è in grado di acquisire e recuperare i dati dalle applicazioni client durante l'intero processo di aggiornamento. Se si approvano tutti i nodi dello stesso tipo per l'aggiornamento (ad esempio, i nodi di storage), i nodi vengono disattivati uno alla volta, in modo che non vi sia tempo in cui tutti i nodi di griglia o tutti i nodi di griglia di un determinato tipo non siano disponibili.

Per consentire la disponibilità continua, assicurarsi che il criterio ILM contenga regole che specificano la memorizzazione di più copie di ciascun oggetto. È inoltre necessario assicurarsi che tutti i client S3 o Swift esterni siano configurati per inviare richieste a uno dei seguenti:

* Un indirizzo IP virtuale del gruppo ad alta disponibilità (ha)
* Bilanciamento del carico di terze parti ad alta disponibilità
* Nodi gateway multipli per ogni client
* Più nodi di storage per ogni client




== Il firmware dell'appliance viene aggiornato

Durante l'aggiornamento a StorageGRID 11.7:

* Tutti i nodi appliance StorageGRID vengono aggiornati automaticamente alla versione 3.7 del firmware del programma di installazione dell'appliance StorageGRID.
* Le appliance SG6060 e SGF6024 vengono aggiornate automaticamente alla versione del firmware del BIOS 3B07.EX e alla versione del firmware BMC 3.97.07.
* Le appliance SG100 e SG1000 vengono aggiornate automaticamente alla versione del firmware del BIOS 3B12.EC e alla versione del firmware BMC 4.71.07.




== Potrebbero essere attivati degli avvisi

Gli avvisi potrebbero essere attivati all'avvio e all'arresto dei servizi e quando il sistema StorageGRID funziona come ambiente a versione mista (alcuni nodi di griglia che eseguono una versione precedente, mentre altri sono stati aggiornati a una versione successiva). Al termine dell'aggiornamento potrebbero essere attivati altri avvisi.

Ad esempio, potrebbe essere visualizzato l'avviso *Impossibile comunicare con il nodo* quando i servizi vengono arrestati oppure l'avviso *errore di comunicazione Cassandra* quando alcuni nodi sono stati aggiornati a StorageGRID 11.7 ma altri nodi eseguono ancora StorageGRID 11.6. In generale, questi avvisi verranno visualizzati al termine dell'aggiornamento.

L'avviso *ILM placement unachievable* potrebbe essere attivato quando i nodi di storage vengono arrestati durante l'aggiornamento a StorageGRID 11.7. Questo avviso potrebbe persistere per 1 giorno dopo il completamento dell'aggiornamento.

Una volta completato l'aggiornamento, è possibile rivedere gli avvisi relativi all'aggiornamento selezionando *Avvisi risolti di recente* o *Avvisi correnti* dalla dashboard di Grid Manager.



== Vengono generate molte notifiche SNMP

Tenere presente che è possibile che vengano generate numerose notifiche SNMP quando i nodi della griglia vengono arrestati e riavviati durante l'aggiornamento. Per evitare notifiche eccessive, deselezionare la casella di controllo *Enable SNMP Agent Notifications* (*CONFIGURATION* > *Monitoring* > *SNMP Agent*) per disattivare le notifiche SNMP prima di avviare l'aggiornamento. Quindi, riattivare le notifiche al termine dell'aggiornamento.



== Le modifiche alla configurazione sono limitate


NOTE: Questo elenco si applica in particolare agli aggiornamenti da StorageGRID 11.6 a StorageGRID 11.7. Se si esegue l'aggiornamento a un'altra release di StorageGRID, fare riferimento all'elenco delle modifiche limitate nelle istruzioni di aggiornamento per tale release.

Fino al completamento dell'attività *Enable New Feature*:

* Non apportare modifiche alla configurazione della griglia.
* Non attivare o disattivare nuove funzioni. Ad esempio, non tentare di creare una connessione a federazione di griglie fino a quando entrambi i sistemi StorageGRID non sono stati aggiornati a StorageGRID 11.7.
* Non aggiornare la configurazione ILM. In caso contrario, potrebbe verificarsi un comportamento ILM inconsistente e imprevisto.
* Non applicare una correzione rapida o ripristinare un nodo della griglia.
+

NOTE: Contattare il supporto tecnico se è necessario ripristinare un nodo durante l'aggiornamento.

* Durante l'aggiornamento a StorageGRID 11.7, non è necessario gestire gruppi ha, interfacce VLAN o endpoint di bilanciamento del carico.
* Non eliminare alcun gruppo ha fino al completamento dell'aggiornamento a StorageGRID 11.7. Gli indirizzi IP virtuali in altri gruppi ha potrebbero diventare inaccessibili.


Fino al completamento dell'attività *fasi finali dell'aggiornamento*:

* Non eseguire una procedura di espansione.
* Non eseguire una procedura di decommissionamento.




== Non puoi visualizzare i dettagli del bucket o gestire i bucket dal tenant Manager

Durante l'aggiornamento a StorageGRID 11.7 (ovvero, mentre il sistema opera come ambiente a versione mista), non è possibile visualizzare i dettagli del bucket o gestire i bucket utilizzando il gestore tenant. Nella pagina Bucket di Tenant Manager viene visualizzato uno dei seguenti errori:

* Non puoi utilizzare questa API durante l'aggiornamento alla versione 11.7.
* Durante l'aggiornamento alla versione 11.7, non è possibile visualizzare i dettagli della versione del bucket in Tenant Manager.


Questo errore viene risolto al termine dell'aggiornamento alla versione 11.7.

.Soluzione alternativa
Mentre è in corso l'aggiornamento 11.7, utilizza i seguenti strumenti per visualizzare i dettagli del bucket o gestire i bucket, invece di utilizzare il Tenant Manager:

* Per eseguire operazioni S3 standard su un bucket, utilizzare link:../s3/operations-on-buckets.html["API REST S3"] o il link:../tenant/understanding-tenant-management-api.html["API di gestione del tenant"].
* Per eseguire operazioni personalizzate di StorageGRID su un bucket (ad esempio, visualizzazione e modifica del livello di coerenza del bucket, attivazione o disattivazione degli ultimi aggiornamenti dell'ora di accesso o configurazione dell'integrazione della ricerca), utilizzare l'API di gestione tenant.




== Le configurazioni di crittografia TLS o SSH potrebbero cambiare

Se le configurazioni di crittografia TLS o SSH sono state modificate manualmente o sono incoerenti tra i nodi, tutti i nodi saranno sovrascritti per essere compatibilità legacy o compatibilità moderna dopo l'aggiornamento. Se è stato utilizzato `fips-ciphers.sh` In StorageGRID 11.6, il criterio Common Criteria viene applicato a tutti i nodi. In caso contrario, viene applicato il criterio di compatibilità legacy. Se si richiedono configurazioni convalidate Common Criteria, è necessario utilizzare il criterio Common Criteria o il criterio FIPS Strict. Se non è stato utilizzato `fips-ciphers.sh`, È necessario utilizzare la nuova impostazione di compatibilità moderna al termine dell'aggiornamento. Per configurare le crittografia, andare a *CONFIGURATION* > *Security* > *Security settings* e selezionare *TLS and SSH policy*.



== Le porte CLB potrebbero essere convertite in endpoint di bilanciamento del carico

Il servizio bilanciamento del carico di connessione (CLB) legacy è stato rimosso in StorageGRID 11.7. Se la configurazione CLB viene rilevata durante i controlli preliminari dell'aggiornamento, viene attivato l'avviso *rilevamento attività bilanciamento carico CLB legacy*. Se sono stati impostati certificati personalizzati per l'API S3 o Swift nella versione StorageGRID esistente, le porte CLB 8082, 8083, 8084 e 8085 verranno convertite in endpoint del bilanciamento del carico durante l'aggiornamento a StorageGRID 11.7.

Vedere anche link:../admin/managing-load-balancing.html["Considerazioni per il bilanciamento del carico"].
