---
permalink: ubuntu/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create ubuntu or debian node configuration files 
summary: I file di configurazione dei nodi sono piccoli file di testo che forniscono le informazioni necessarie al servizio host StorageGRID per avviare un nodo e collegarlo alla rete appropriata e bloccare le risorse di storage. I file di configurazione dei nodi vengono utilizzati per i nodi virtuali e non per i nodi appliance. 
---
= Creare file di configurazione del nodo per le distribuzioni Ubuntu o Debian
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I file di configurazione dei nodi sono piccoli file di testo che forniscono le informazioni necessarie al servizio host StorageGRID per avviare un nodo e collegarlo alla rete appropriata e bloccare le risorse di storage. I file di configurazione dei nodi vengono utilizzati per i nodi virtuali e non per i nodi appliance.



== Dove si possono inserire i file di configurazione del nodo?

È necessario inserire il file di configurazione per ciascun nodo StorageGRID in `/etc/storagegrid/nodes` directory sull'host in cui verrà eseguito il nodo. Ad esempio, se si intende eseguire un nodo Admin, un nodo Gateway e un nodo Storage sull'host, è necessario inserire tre file di configurazione del nodo `/etc/storagegrid/nodes` Su host. È possibile creare i file di configurazione direttamente su ciascun host utilizzando un editor di testo, ad esempio vim o nano, oppure crearli altrove e spostarli su ciascun host.



== Quali sono i nomi dei file di configurazione del nodo?

I nomi dei file di configurazione sono significativi. Il formato è `node-name.conf`, dove `node-name` è un nome assegnato al nodo. Questo nome viene visualizzato nel programma di installazione di StorageGRID e viene utilizzato per le operazioni di manutenzione dei nodi, ad esempio la migrazione dei nodi.

I nomi dei nodi devono seguire queste regole:

* Deve essere unico
* Deve iniziare con una lettera
* Può contenere i caratteri Da A a Z e da a a z
* Può contenere i numeri da 0 a 9
* Può contenere uno o più trattini (-)
* Non deve contenere più di 32 caratteri, ad eccezione di `.conf` interno


Qualsiasi file in `/etc/storagegrid/nodes` che non seguono queste convenzioni di denominazione non verranno analizzata dal servizio host.

Se è stata pianificata una topologia multi-sito per il proprio grid, uno schema di denominazione tipico dei nodi potrebbe essere:

[listing]
----
site-nodetype-nodenumber.conf
----
Ad esempio, è possibile utilizzare `dc1-adm1.conf` Per il primo nodo Admin nel data center 1, e. `dc2-sn3.conf` Per il terzo nodo di storage nel data center 2. Tuttavia, è possibile utilizzare qualsiasi schema desiderato, purché tutti i nomi dei nodi seguano le regole di denominazione.



== Cosa si trova in un file di configurazione del nodo?

I file di configurazione contengono coppie chiave/valore, con una chiave e un valore per riga. Per ogni coppia chiave/valore, è necessario attenersi alle seguenti regole:

* La chiave e il valore devono essere separati da un segno di uguale (`=`) e spazio vuoto opzionale.
* Le chiavi non possono contenere spazi.
* I valori possono contenere spazi incorporati.
* Qualsiasi spazio iniziale o finale viene ignorato.


Alcune chiavi sono necessarie per ogni nodo, mentre altre sono facoltative o richieste solo per alcuni tipi di nodo.

La tabella definisce i valori accettabili per tutte le chiavi supportate. Nella colonna centrale:

*R*: Obbligatorio + BP: Best practice + o: Facoltativo

[cols="2a,1a,4a"]
|===
| Chiave | R, BP O O? | Valore 


 a| 
ADMIN_IP
 a| 
BP
 a| 
Grid Network IPv4 address del nodo di amministrazione principale per la griglia a cui appartiene questo nodo. Utilizzare lo stesso valore specificato per GRID_NETWORK_IP per il nodo Grid con NODE_TYPE = VM_Admin_Node e ADMIN_ROLE = Primary. Se si omette questo parametro, il nodo tenta di rilevare un nodo Admin primario utilizzando mDNS.

link:how-grid-nodes-discover-primary-admin-node.html["In che modo i nodi della griglia rilevano il nodo di amministrazione primario"]

*Nota*: Questo valore viene ignorato e potrebbe essere proibito sul nodo di amministrazione primario.



 a| 
ADMIN_NETWORK_CONFIG
 a| 
O
 a| 
DHCP, STATICO O DISATTIVATO



 a| 
ADMIN_NETWORK_ESL
 a| 
O
 a| 
Elenco separato da virgole delle subnet nella notazione CIDR a cui il nodo deve comunicare utilizzando il gateway Admin Network.

Esempio: `172.16.0.0/21,172.17.0.0/21`



 a| 
ADMIN_NETWORK_GATEWAY
 a| 
O (*R*)
 a| 
Indirizzo IPv4 del gateway Admin Network locale per questo nodo. Deve trovarsi nella subnet definita da ADMIN_NETWORK_IP e ADMIN_NETWORK_MASK. Questo valore viene ignorato per le reti configurate con DHCP.

*Nota*: Questo parametro è obbligatorio se VIENE specificato ADMIN_NETWORK_ESL.

Esempi:

`1.1.1.1`

`10.224.4.81`



 a| 
ADMIN_NETWORK_IP
 a| 
O
 a| 
Indirizzo IPv4 di questo nodo nella rete di amministrazione. Questa chiave è necessaria solo quando ADMIN_NETWORK_CONFIG = STATIC; non specificarla per altri valori.

Esempi:

`1.1.1.1`

`10.224.4.81`



 a| 
ADMIN_NETWORK_MAC
 a| 
O
 a| 
L'indirizzo MAC dell'interfaccia Admin Network nel contenitore.

Questo campo è facoltativo. Se omesso, viene generato automaticamente un indirizzo MAC.

Devono essere 6 coppie di cifre esadecimali separate da due punti.

Esempio: `b2:9c:02:c2:27:10`



 a| 
ADMIN_NETWORK_MASK
 a| 
O
 a| 
Netmask IPv4 per questo nodo, sulla rete di amministrazione. Questa chiave è necessaria solo quando ADMIN_NETWORK_CONFIG = STATIC; non specificarla per altri valori.

Esempi:

`255.255.255.0`

`255.255.248.0`



 a| 
ADMIN_NETWORK_MTU
 a| 
O
 a| 
MTU (Maximum Transmission Unit) per questo nodo nella rete di amministrazione. Non specificare se ADMIN_NETWORK_CONFIG = DHCP. Se specificato, il valore deve essere compreso tra 1280 e 9216. Se omesso, viene utilizzato 1500.

Se si desidera utilizzare i frame jumbo, impostare la MTU su un valore adatto per i frame jumbo, ad esempio 9000. In caso contrario, mantenere il valore predefinito.

*IMPORTANTE*: Il valore MTU della rete deve corrispondere al valore configurato sulla porta dello switch a cui è connesso il nodo. In caso contrario, potrebbero verificarsi problemi di performance di rete o perdita di pacchetti.

Esempi:

`1500`

`8192`



 a| 
ADMIN_NETWORK_TARGET
 a| 
BP
 a| 
Nome del dispositivo host che verrà utilizzato per l'accesso alla rete amministrativa dal nodo StorageGRID. Sono supportati solo i nomi delle interfacce di rete. In genere, si utilizza un nome di interfaccia diverso da quello specificato per GRID_NETWORK_TARGET o CLIENT_NETWORK_TARGET.

*Nota*: Non utilizzare dispositivi bond o bridge come destinazione di rete. Configurare una VLAN (o un'altra interfaccia virtuale) sulla parte superiore del dispositivo bond oppure utilizzare una coppia di bridge e Virtual Ethernet (veth).

*Best practice*:specificare un valore anche se questo nodo inizialmente non dispone di un indirizzo IP Admin Network. Quindi, è possibile aggiungere un indirizzo IP Admin Network in un secondo momento, senza dover riconfigurare il nodo sull'host.

Esempi:

`bond0.1002`

`ens256`



 a| 
ADMIN_NETWORK_TARGET_TYPE
 a| 
O
 a| 
Interfaccia

(Questo è l'unico valore supportato).



 a| 
ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC
 a| 
BP
 a| 
Vero o Falso

Impostare la chiave su "true" per fare in modo che il container StorageGRID utilizzi l'indirizzo MAC dell'interfaccia host di destinazione sulla rete di amministrazione.

*Best practice:* nelle reti in cui sarebbe richiesta la modalità promiscua, utilizzare la chiave ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Per ulteriori informazioni sulla clonazione MAC:

link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerazioni e consigli per la clonazione degli indirizzi MAC (Red Hat Enterprise Linux o CentOS)"]

link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerazioni e raccomandazioni per la clonazione degli indirizzi MAC (Ubuntu o Debian)"]



 a| 
RUOLO_AMMINISTRATORE
 a| 
*R*
 a| 
Primario o non primario

Questa chiave è necessaria solo quando NODE_TYPE = VM_Admin_Node; non specificarla per altri tipi di nodo.



 a| 
BLOCK_DEVICE_AUDIT_LOGS
 a| 
*R*
 a| 
Percorso e nome del file speciale del dispositivo a blocchi utilizzato da questo nodo per la memorizzazione persistente dei registri di controllo. Questa chiave è necessaria solo per i nodi con NODE_TYPE = VM_Admin_Node; non specificarla per altri tipi di nodo.

Esempi:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`



 a| 
BLOCK_DEVICE_RANGEDB_000

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015
 a| 
*R*
 a| 
Percorso e nome del file speciale del dispositivo a blocchi utilizzato da questo nodo per lo storage a oggetti persistente. Questa chiave è necessaria solo per i nodi con NODE_TYPE = VM_Storage_Node; non specificarla per altri tipi di nodo.

È necessario solo BLOCK_DEVICE_RANGEDB_000; gli altri sono facoltativi. Il dispositivo a blocchi specificato per BLOCK_DEVICE_RANGEDB_000 deve essere di almeno 4 TB; gli altri possono essere più piccoli.

Non lasciare lacune. Se si specifica BLOCK_DEVICE_RANGEDB_005, è necessario specificare ANCHE BLOCK_DEVICE_RANGEDB_004.

*Nota*: Per la compatibilità con le implementazioni esistenti, sono supportate chiavi a due cifre per i nodi aggiornati.

Esempi:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`



 a| 
BLOCK_DEVICE_TABLES
 a| 
*R*
 a| 
Percorso e nome del file speciale del dispositivo a blocchi utilizzato da questo nodo per l'archiviazione persistente delle tabelle di database. Questa chiave è necessaria solo per i nodi con NODE_TYPE = VM_Admin_Node; non specificarla per altri tipi di nodo.

Esempi:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`



 a| 
BLOCK_DEVICE_VAR_LOCAL
 a| 
*R*
 a| 
Percorso e nome del file speciale del dispositivo a blocchi che verrà utilizzato da questo nodo per lo storage persistente /var/local.

Esempi:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`



 a| 
CONFIGURAZIONE_RETE_CLIENT
 a| 
O
 a| 
DHCP, STATICO O DISATTIVATO



 a| 
GATEWAY_RETE_CLIENT
 a| 
O
 a| 
Indirizzo IPv4 del gateway di rete client locale per questo nodo, che deve trovarsi sulla subnet definita da CLIENT_NETWORK_IP e CLIENT_NETWORK_MASK. Questo valore viene ignorato per le reti configurate con DHCP.

Esempi:

`1.1.1.1`

`10.224.4.81`



 a| 
IP_RETE_CLIENT
 a| 
O
 a| 
Indirizzo IPv4 di questo nodo sulla rete client. Questa chiave è necessaria solo quando CLIENT_NETWORK_CONFIG = STATIC; non specificarla per altri valori.

Esempi:

`1.1.1.1`

`10.224.4.81`



 a| 
CLIENT_NETWORK_MAC
 a| 
O
 a| 
L'indirizzo MAC dell'interfaccia di rete client nel contenitore.

Questo campo è facoltativo. Se omesso, viene generato automaticamente un indirizzo MAC.

Devono essere 6 coppie di cifre esadecimali separate da due punti.

Esempio: `b2:9c:02:c2:27:20`



 a| 
CLIENT_NETWORK_MASK
 a| 
O
 a| 
Netmask IPv4 per questo nodo sulla rete client. Questa chiave è necessaria solo quando CLIENT_NETWORK_CONFIG = STATIC; non specificarla per altri valori.

Esempi:

`255.255.255.0`

`255.255.248.0`



 a| 
MTU_RETE_CLIENT
 a| 
O
 a| 
MTU (Maximum Transmission Unit) per questo nodo sulla rete client. Non specificare se CLIENT_NETWORK_CONFIG = DHCP. Se specificato, il valore deve essere compreso tra 1280 e 9216. Se omesso, viene utilizzato 1500.

Se si desidera utilizzare i frame jumbo, impostare la MTU su un valore adatto per i frame jumbo, ad esempio 9000. In caso contrario, mantenere il valore predefinito.

*IMPORTANTE*: Il valore MTU della rete deve corrispondere al valore configurato sulla porta dello switch a cui è connesso il nodo. In caso contrario, potrebbero verificarsi problemi di performance di rete o perdita di pacchetti.

Esempi:

`1500`

`8192`



 a| 
DESTINAZIONE_RETE_CLIENT
 a| 
BP
 a| 
Nome del dispositivo host che verrà utilizzato per l'accesso alla rete client dal nodo StorageGRID. Sono supportati solo i nomi delle interfacce di rete. In genere, si utilizza un nome di interfaccia diverso da quello specificato per GRID_NETWORK_TARGET o ADMIN_NETWORK_TARGET.

*Nota*: Non utilizzare dispositivi bond o bridge come destinazione di rete. Configurare una VLAN (o un'altra interfaccia virtuale) sulla parte superiore del dispositivo bond oppure utilizzare una coppia di bridge e Virtual Ethernet (veth).

*Best practice:* specificare un valore anche se questo nodo inizialmente non avrà un indirizzo IP di rete client. Quindi, è possibile aggiungere un indirizzo IP di rete client in un secondo momento, senza dover riconfigurare il nodo sull'host.

Esempi:

`bond0.1003`

`ens423`



 a| 
TIPO_DESTINAZIONE_RETE_CLIENT
 a| 
O
 a| 
Interfaccia

(Questo è solo un valore supportato).



 a| 
CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC
 a| 
BP
 a| 
Vero o Falso

Impostare la chiave su "true" per fare in modo che il container StorageGRID utilizzi l'indirizzo MAC dell'interfaccia di destinazione host sulla rete client.

*Best practice:* nelle reti in cui sarebbe richiesta la modalità promiscua, utilizzare invece la chiave CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Per ulteriori informazioni sulla clonazione MAC:

link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerazioni e consigli per la clonazione degli indirizzi MAC (Red Hat Enterprise Linux o CentOS)"]

link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerazioni e raccomandazioni per la clonazione degli indirizzi MAC (Ubuntu o Debian)"]



 a| 
GRID_NETWORK_CONFIG
 a| 
BP
 a| 
STATICO o DHCP

(Il valore predefinito è STATICO se non specificato).



 a| 
GRID_NETWORK_GATEWAY
 a| 
*R*
 a| 
Indirizzo IPv4 del gateway Grid Network locale per questo nodo, che deve trovarsi sulla subnet definita da GRID_NETWORK_IP e GRID_NETWORK_MASK. Questo valore viene ignorato per le reti configurate con DHCP.

Se Grid Network è una singola subnet senza gateway, utilizzare l'indirizzo del gateway standard per la subnet (X. YY.Z.1) o il valore GRID_NETWORK_IP di questo nodo; entrambi i valori semplificheranno le future espansioni Grid Network.



 a| 
IP_RETE_GRIGLIA
 a| 
*R*
 a| 
Indirizzo IPv4 di questo nodo sulla rete griglia. Questa chiave è necessaria solo quando GRID_NETWORK_CONFIG = STATIC; non specificarla per altri valori.

Esempi:

`1.1.1.1`

`10.224.4.81`



 a| 
GRID_NETWORK_MAC
 a| 
O
 a| 
L'indirizzo MAC dell'interfaccia Grid Network nel contenitore.

Questo campo è facoltativo. Se omesso, viene generato automaticamente un indirizzo MAC.

Devono essere 6 coppie di cifre esadecimali separate da due punti.

Esempio: `b2:9c:02:c2:27:30`



 a| 
GRID_NETWORK_MASK
 a| 
O
 a| 
Netmask IPv4 per questo nodo sulla rete griglia. Questa chiave è necessaria solo quando GRID_NETWORK_CONFIG = STATIC; non specificarla per altri valori.

Esempi:

`255.255.255.0`

`255.255.248.0`



 a| 
GRID_NETWORK_MTU
 a| 
O
 a| 
MTU (Maximum Transmission Unit) per questo nodo sulla rete di rete. Non specificare se GRID_NETWORK_CONFIG = DHCP. Se specificato, il valore deve essere compreso tra 1280 e 9216. Se omesso, viene utilizzato 1500.

Se si desidera utilizzare i frame jumbo, impostare la MTU su un valore adatto per i frame jumbo, ad esempio 9000. In caso contrario, mantenere il valore predefinito.

*IMPORTANTE*: Il valore MTU della rete deve corrispondere al valore configurato sulla porta dello switch a cui è connesso il nodo. In caso contrario, potrebbero verificarsi problemi di performance di rete o perdita di pacchetti.

*IMPORTANTE*: Per ottenere le migliori performance di rete, tutti i nodi devono essere configurati con valori MTU simili sulle interfacce Grid Network. L'avviso *Grid Network MTU mismatch* (mancata corrispondenza MTU rete griglia) viene attivato se si verifica una differenza significativa nelle impostazioni MTU per Grid Network su singoli nodi. I valori MTU non devono essere uguali per tutti i tipi di rete.

Esempi:

1500 8192



 a| 
GRID_NETWORK_TARGET
 a| 
*R*
 a| 
Nome del dispositivo host che verrà utilizzato per l'accesso alla rete griglia dal nodo StorageGRID. Sono supportati solo i nomi delle interfacce di rete. In genere, si utilizza un nome di interfaccia diverso da quello specificato per ADMIN_NETWORK_TARGET o CLIENT_NETWORK_TARGET.

*Nota*: Non utilizzare dispositivi bond o bridge come destinazione di rete. Configurare una VLAN (o un'altra interfaccia virtuale) sulla parte superiore del dispositivo bond oppure utilizzare una coppia di bridge e Virtual Ethernet (veth).

Esempi:

`bond0.1001`

`ens192`



 a| 
GRID_NETWORK_TARGET_TYPE
 a| 
O
 a| 
Interfaccia

(Questo è l'unico valore supportato).



 a| 
GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC
 a| 
*BP*
 a| 
Vero o Falso

Impostare il valore della chiave su "true" per fare in modo che il contenitore StorageGRID utilizzi l'indirizzo MAC dell'interfaccia di destinazione host sulla rete di rete.

*Best practice:* nelle reti in cui sarebbe richiesta la modalità promiscua, utilizzare invece la chiave GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC.

Per ulteriori informazioni sulla clonazione MAC:

link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerazioni e consigli per la clonazione degli indirizzi MAC (Red Hat Enterprise Linux o CentOS)"]

link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Considerazioni e raccomandazioni per la clonazione degli indirizzi MAC (Ubuntu o Debian)"]



 a| 
INTERFACES_TARGET_nnnn
 a| 
O
 a| 
Nome e descrizione opzionale per un'interfaccia aggiuntiva che si desidera aggiungere a questo nodo. È possibile aggiungere più interfacce aggiuntive a ciascun nodo.

Per _nnnn_, specificare un numero univoco per ogni voce INTERFACES_TARGET che si sta aggiungendo.

Per il valore, specificare il nome dell'interfaccia fisica sull'host bare-metal. Quindi, facoltativamente, aggiungere una virgola e fornire una descrizione dell'interfaccia, che viene visualizzata nella pagina delle interfacce VLAN e nella pagina dei gruppi ha.

Ad esempio: `INTERFACES_TARGET_01=ens256, Trunk`

Se si aggiunge un'interfaccia di linea, è necessario configurare un'interfaccia VLAN in StorageGRID. Se si aggiunge un'interfaccia di accesso, è possibile aggiungerla direttamente a un gruppo ha; non è necessario configurare un'interfaccia VLAN.



 a| 
MAXIMUM_RAM
 a| 
O
 a| 
La quantità massima di RAM che questo nodo può consumare. Se questa chiave viene omessa, il nodo non presenta limitazioni di memoria. Quando si imposta questo campo per un nodo a livello di produzione, specificare un valore di almeno 24 GB e da 16 a 32 GB inferiore alla RAM totale di sistema.

*Nota*: Il valore RAM influisce sullo spazio riservato ai metadati effettivi di un nodo. Vedere link:../admin/managing-object-metadata-storage.html["Descrizione di Metadata Reserved Space"].

Il formato di questo campo è `<number><unit>`, dove `<unit>` può essere `b`, `k`, `m`, o. `g`.

Esempi:

`24g`

`38654705664b`

*Nota*: Se si desidera utilizzare questa opzione, è necessario abilitare il supporto del kernel per i gruppi di memoria.



 a| 
NODE_TYPE
 a| 
*R*
 a| 
Tipo di nodo:

VM_Admin_Node VM_Storage_Node VM_Archive_Node VM_API_Gateway



 a| 
PORT_REMAP
 a| 
O
 a| 
Consente di rimapare qualsiasi porta utilizzata da un nodo per comunicazioni interne al nodo di rete o comunicazioni esterne. Il rimapping delle porte è necessario se i criteri di rete aziendali limitano una o più porte utilizzate da StorageGRID, come descritto in link:../network/internal-grid-node-communications.html["Comunicazioni interne al nodo di rete"] oppure link:../network/external-communications.html["Comunicazioni esterne"].

*IMPORTANTE*: Non rimappare le porte che si intende utilizzare per configurare gli endpoint del bilanciamento del carico.

*Nota*: Se è impostato solo PORT_REMAP, il mapping specificato viene utilizzato per le comunicazioni in entrata e in uscita. Se VIENE specificato anche PORT_REMAP_INBOUND, PORT_REMAP si applica solo alle comunicazioni in uscita.

Il formato utilizzato è: `<network type>/<protocol>/<default port used by grid node>/<new port>`, dove `<network type>` è grid, admin o client e il protocollo è tcp o udp.

Ad esempio:

`PORT_REMAP = client/tcp/18082/443`



 a| 
PORT_REMAP_INBOUND
 a| 
O
 a| 
Consente di rimapare le comunicazioni in entrata alla porta specificata. Se si specifica PORT_REMAP_INBOUND ma non si specifica un valore per PORT_REMAP, le comunicazioni in uscita per la porta rimangono invariate.

*IMPORTANTE*: Non rimappare le porte che si intende utilizzare per configurare gli endpoint del bilanciamento del carico.

Il formato utilizzato è: `<network type>/<protocol:>/<remapped port >/<default port used by grid node>`, dove `<network type>` è grid, admin o client e il protocollo è tcp o udp.

Ad esempio:

`PORT_REMAP_INBOUND = grid/tcp/3022/22`

|===