---
permalink: ubuntu/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to prepare for ubuntu or debian installation 
summary: Prima di implementare i nodi grid e configurare la griglia StorageGRID, è necessario conoscere i passaggi e i requisiti per completare la procedura. 
---
= Prima di installare (Ubuntu o Debian)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di implementare i nodi grid e configurare StorageGRID, è necessario conoscere i passaggi e i requisiti per completare la procedura.

Le procedure di implementazione e configurazione di StorageGRID presuppongono una conoscenza dell'architettura e del funzionamento del sistema StorageGRID.

È possibile implementare uno o più siti contemporaneamente; tuttavia, tutti i siti devono soddisfare il requisito minimo di avere almeno tre nodi di storage.

Prima di avviare un'installazione StorageGRID, è necessario:

* Comprendere i requisiti di calcolo, inclusi i requisiti minimi di CPU e RAM per ciascun nodo.
* Scopri come StorageGRID supporta più reti per la separazione del traffico, la sicurezza e la convenienza amministrativa e utilizza un piano per le reti che intendi collegare a ciascun nodo StorageGRID.
+
Vedere StorageGRID link:../network/index.html["Linee guida per il networking"].

* Comprendere i requisiti di storage e performance di ogni tipo di nodo grid.
* Identificare un insieme di server (fisici, virtuali o entrambi) che, in aggregato, forniscono risorse sufficienti per supportare il numero e il tipo di nodi StorageGRID che si intende implementare.
* Comprendere link:node-container-migration-requirements.html["requisiti per la migrazione dei nodi"], se si desidera eseguire la manutenzione pianificata sugli host fisici senza alcuna interruzione del servizio.
* Raccogliere tutte le informazioni di rete in anticipo. A meno che non si utilizzi DHCP, raccogliere gli indirizzi IP da assegnare a ciascun nodo della griglia e gli indirizzi IP dei server DNS e NTP che verranno utilizzati.
* Installazione, connessione e configurazione di tutto l'hardware richiesto, incluse eventuali appliance StorageGRID, in base alle specifiche.
+

IMPORTANT: Se l'installazione di StorageGRID non utilizza nodi di storage (hardware) dell'appliance StorageGRID, è necessario utilizzare lo storage RAID hardware con cache di scrittura supportata dalla batteria (BBWC). StorageGRID non supporta l'utilizzo di reti VSAN (Virtual Storage Area Network), RAID software o nessuna protezione RAID.

+

NOTE: Le istruzioni di installazione e integrazione specifiche dell'hardware non sono incluse nella procedura di installazione di StorageGRID. Per informazioni su come installare le appliance StorageGRID, vedere link:../installconfig/index.html["Installare l'hardware dell'appliance"].

* Decidere quali strumenti di implementazione e configurazione si desidera utilizzare.

