---
permalink: installconfig/configuring-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, configure, setup, set up 
summary: 'L"interfaccia utente del controller di gestione della scheda base (BMC) sull"appliance SGF6112, SG6000 o Services fornisce informazioni sullo stato dell"hardware e consente di configurare le impostazioni SNMP e altre opzioni per le appliance.' 
---
= Interfaccia BMC: Panoramica (SGF6112, SG6000, SG100 e SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente per il controller di gestione della scheda base (BMC) sull'appliance SGF6112, SG6000 o Services fornisce informazioni sullo stato dell'hardware e consente di configurare le impostazioni SNMP e altre opzioni per le appliance.

Per configurare il BMC durante l'installazione dell'appliance, attenersi alle seguenti procedure descritte in questa sezione:

* link:../installconfig/changing-root-password-for-bmc-interface.html["Modificare la password root per l'interfaccia BMC"]
* link:../installconfig/setting-ip-address-for-bmc-management-port.html["Impostare l'indirizzo IP per la porta di gestione BMC"]
* link:../installconfig/accessing-bmc-interface.html["Accedere all'interfaccia BMC"]
* link:../installconfig/configuring-snmp-settings-for-bmc.html["Configurare le impostazioni SNMP"]
* link:../installconfig/setting-up-email-notifications-for-alerts.html["Impostare le notifiche e-mail per gli avvisi BMC"]


[NOTE]
====
Se l'appliance è già stata installata in una griglia e sta eseguendo il software StorageGRID, attenersi alle seguenti procedure:

* link:../commonhardware/placing-appliance-into-maintenance-mode.html["Impostare l'apparecchio in modalità di manutenzione"] Per accedere al programma di installazione dell'appliance StorageGRID.
* Vedere link:../installconfig/setting-ip-address-for-bmc-management-port.html["Impostare l'indirizzo IP per la porta di gestione BMC"] Per informazioni sull'accesso all'interfaccia BMC tramite il programma di installazione dell'appliance StorageGRID.


====