---
permalink: installconfig/viewing-error-codes-for-sg1000-controller-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, error codes, errors, error, codes, bmc 
summary: 'Se si verifica un errore hardware durante l"avvio dell"appliance, BMC registra un codice di errore. Se necessario, è possibile visualizzare questi codici di errore utilizzando l"interfaccia BMC, quindi collaborare con il supporto tecnico per risolvere il problema.' 
---
= Visualizzazione dei codici di errore (SG100 e SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si verifica un errore hardware durante l'avvio dell'appliance, BMC registra un codice di errore. Se necessario, è possibile visualizzare questi codici di errore utilizzando l'interfaccia BMC, quindi collaborare con il supporto tecnico per risolvere il problema.

.Prima di iniziare
* Sai come accedere alla dashboard BMC.


.Fasi
. Dalla dashboard BMC, selezionare *BIOS POST Code* (Codice POST BIOS).
. Esaminare le informazioni visualizzate per il codice corrente e il codice precedente.
+
Se viene visualizzato uno dei seguenti codici di errore, collaborare con il supporto tecnico per risolvere il problema.

+
[cols="1a,3a"]
|===
| Codice | Indica 


 a| 
0x0E
 a| 
Microcodice non trovato



 a| 
0x0F
 a| 
Microcodice non caricato



 a| 
0x50
 a| 
Errore di inizializzazione della memoria. Tipo di memoria non valido o velocità della memoria incompatibile.



 a| 
0x51
 a| 
Errore di inizializzazione della memoria. Lettura SPD non riuscita.



 a| 
0x52
 a| 
Errore di inizializzazione della memoria. Le dimensioni della memoria non sono valide o i moduli di memoria non corrispondono.



 a| 
0x53
 a| 
Errore di inizializzazione della memoria. Nessuna memoria utilizzabile rilevata.



 a| 
0x54
 a| 
Errore di inizializzazione della memoria non specificato



 a| 
0x55
 a| 
Memoria non installata



 a| 
0x56
 a| 
Tipo di CPU o velocità non validi



 a| 
0x57
 a| 
Mancata corrispondenza della CPU



 a| 
0x58
 a| 
Test automatico della CPU non riuscito o possibile errore della cache della CPU



 a| 
0x59
 a| 
Il microcodice della CPU non è stato trovato o l'aggiornamento del microcodice non è riuscito



 a| 
0x5A
 a| 
Errore CPU interno



 a| 
0x5B
 a| 
Reset PPI is not available (Ripristina PPI non disponibile)



 a| 
0x5C
 a| 
Test automatico BMC fase PEI non riuscito



 a| 
0xD0
 a| 
Errore di inizializzazione della CPU



 a| 
0xD1
 a| 
Errore di inizializzazione North Bridge



 a| 
0xD2
 a| 
Errore di inizializzazione del South Bridge



 a| 
0xd3
 a| 
Alcuni protocolli architettonici non sono disponibili



 a| 
0xD4
 a| 
Errore di allocazione delle risorse PCI. Risorse esaurite.



 a| 
0xD5
 a| 
Spazio non disponibile per la Option ROM legacy



 a| 
0xD6
 a| 
Nessun dispositivo di output della console trovato



 a| 
0xD7
 a| 
Nessun dispositivo di input console trovato



 a| 
0xD8
 a| 
Password non valida



 a| 
0xD9
 a| 
Errore durante il caricamento dell'opzione di avvio (errore restituito da LoadImage)



 a| 
0xDA
 a| 
Opzione di boot non riuscita (errore restituito da startimage)



 a| 
0xDB
 a| 
Aggiornamento flash non riuscito



 a| 
0xDC
 a| 
Il protocollo di reset non è disponibile



 a| 
0xDD
 a| 
Errore di autotest BMC fase DXE



 a| 
0xE8
 a| 
MRC: ERR_NO_MEMORY



 a| 
0xE9
 a| 
MRC: ERR_LT_LOCK



 a| 
0xEA
 a| 
MRC: ERR_DDR_INIT



 a| 
0xEB
 a| 
MRC: ERR_MEM_TEST



 a| 
0xEC
 a| 
MRC: ERR_VENDOR_SPECIFIC



 a| 
0xED
 a| 
MRC: ERR_DIMM_COMPAT



 a| 
0xEE
 a| 
MRC: ERR_MRC_COMPATIBILITY



 a| 
0 x EF
 a| 
MRC: ERR_MRC_STRUCT



 a| 
0xF0
 a| 
MRC: ERR_SET_VDD



 a| 
0xF1
 a| 
MRC: BUFFER ERR_IOT_MEM



 a| 
0xF2
 a| 
MRC: ERR_RC_INTERNAL



 a| 
0xF3
 a| 
MRC: ERR_INVALID_REG_ACCESS



 a| 
0xF4
 a| 
MRC: ERR_SET_MC_FREQ



 a| 
0xF5
 a| 
MRC: ERR_READ_MC_FREQ



 a| 
0x70
 a| 
MRC: ERR_DIMM_CHANNEL



 a| 
0x74
 a| 
MRC: ERR_BIST_CHECK



 a| 
0xF6
 a| 
MRC: ERR_SMBUS



 a| 
0xF7
 a| 
MRC: ERR_PCU



 a| 
0xF8
 a| 
MRC: ERR_NGN



 a| 
0xF9
 a| 
MRC: ERR_INTERLEAVE_FAILURE

|===

