---
permalink: installconfig/viewing-boot-up-codes-for-appliance-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, boot codes, boot-up codes, start codes, codes, boot, start, bmc 
summary: 'Quando si alimenta l"appliance, il BMC registra una serie di codici di avvio. È possibile visualizzare questi codici su una console grafica collegata alla porta di gestione BMC.' 
---
= Visualizzazione dei codici di avvio (SG100 e SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si alimenta l'appliance, il BMC registra una serie di codici di avvio. È possibile visualizzare questi codici su una console grafica collegata alla porta di gestione BMC.

.Prima di iniziare
* Sai come accedere alla dashboard BMC.
* Se si desidera utilizzare Serial-over-LAN (Sol), si ha esperienza nell'utilizzo delle applicazioni della console IPMI Sol.


.Fasi
. Selezionare uno dei seguenti metodi per visualizzare i codici di avvio del controller dell'appliance e raccogliere l'apparecchiatura richiesta.
+
[cols="1a,2a"]
|===
| Metodo | Attrezzatura necessaria 


 a| 
Console VGA
 a| 
** Monitor con supporto VGA
** Cavo VGA




 a| 
KVM
 a| 
** Cavo RJ-45




 a| 
Porta seriale
 a| 
** CAVO seriale DB-9
** Terminale seriale virtuale




 a| 
SOL
 a| 
** Terminale seriale virtuale


|===
. Se si utilizza una console VGA, attenersi alla seguente procedura:
+
.. Collegare un monitor VGA alla porta VGA sul retro dell'apparecchio.
.. Visualizzare i codici visualizzati sul monitor.


. Se si utilizza BMC KVM, attenersi alla seguente procedura:
+
.. Connettersi alla porta di gestione BMC e accedere all'interfaccia Web BMC.
.. Selezionare *telecomando*.
.. Avviare il KVM.
.. Visualizzare i codici sul monitor virtuale.


. Se si utilizza una porta seriale e un terminale, attenersi alla seguente procedura:
+
.. Collegare alla porta seriale DB-9 sul retro dell'appliance.
.. Utilizzare le impostazioni `115200 8-N-1`.
.. Visualizzare i codici stampati sul terminale seriale.


. Se si utilizza Sol, attenersi alla seguente procedura:
+
.. Connettersi a IPMI Sol utilizzando l'indirizzo IP BMC e le credenziali di accesso.
+
`ipmitool -I lanplus -H _BMC_Port_IP_ -U admin -P _Password_ sol activate`

+

NOTE: In alcuni casi il nome utente predefinito potrebbe essere `root` invece di `admin`.

.. Visualizzare i codici sul terminale seriale virtuale.


. Utilizza la tabella per cercare i codici dell'apparecchio.
+
[cols="1a,3a"]
|===
| Codice | Indica 


 a| 
CIAO
 a| 
Lo script di boot master è stato avviato.



 a| 
HP
 a| 
Il sistema sta verificando se il firmware della scheda di interfaccia di rete (NIC) deve essere aggiornato.



 a| 
RB
 a| 
Il sistema viene riavviato dopo l'applicazione degli aggiornamenti del firmware.



 a| 
FP
 a| 
I controlli di aggiornamento del firmware del sottosistema hardware sono stati completati. Avvio dei servizi di comunicazione tra controller in corso.



 a| 
HC
 a| 
Il sistema sta verificando la presenza di dati di installazione di StorageGRID.



 a| 
HO
 a| 
L'appliance StorageGRID è in esecuzione.



 a| 
HA
 a| 
StorageGRID è in esecuzione.

|===


.Informazioni correlate
link:../installconfig/accessing-bmc-interface.html["Accedere all'interfaccia BMC"]
