---
permalink: network/appliance-nodes.html 
sidebar: sidebar 
keywords: networking for appliance, port bond mode 
summary: È possibile configurare le porte di rete sulle appliance StorageGRID in modo che utilizzino le modalità di port bond che soddisfano i requisiti di throughput, ridondanza e failover. 
---
= Nodi appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare le porte di rete sulle appliance StorageGRID in modo che utilizzino le modalità di port bond che soddisfano i requisiti di throughput, ridondanza e failover.

Le porte 10/25-GbE delle appliance StorageGRID possono essere configurate in modalità bond fissa o aggregata per le connessioni alla rete grid e alla rete client.

Le porte di Admin Network 1-GbE possono essere configurate in modalità indipendente o Active-Backup per le connessioni alla rete di amministrazione.

Consultare le informazioni relative alle modalità di port bond dell'appliance:

* link:../installconfig/port-bond-modes-for-sgf6112.html["Modalità di port bond (SGF6112)"]
* link:../installconfig/port-bond-modes-for-sg6000-cn-controller.html["Modalità Port Bond (controller SG6000-CN)"]
* link:../installconfig/port-bond-modes-for-e5700sg-controller-ports.html["Modalità Port Bond (controller E5700SG)"]
* link:../installconfig/port-bond-modes-for-sg100-and-sg1000.html["Modalità Port Bond (SG100 e SG1000)"]

