---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 'Prima di creare un gruppo tenant, prendere in considerazione le autorizzazioni che si desidera assegnare a tale gruppo. Le autorizzazioni di gestione del tenant determinano le attività che gli utenti possono eseguire utilizzando il tenant Manager o l"API di gestione del tenant. Un utente può appartenere a uno o più gruppi. Le autorizzazioni sono cumulative se un utente appartiene a più gruppi.' 
---
= Permessi di gestione del tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di creare un gruppo tenant, prendere in considerazione le autorizzazioni che si desidera assegnare a tale gruppo. Le autorizzazioni di gestione del tenant determinano le attività che gli utenti possono eseguire utilizzando il tenant Manager o l'API di gestione del tenant. Un utente può appartenere a uno o più gruppi. Le autorizzazioni sono cumulative se un utente appartiene a più gruppi.

Per accedere a tenant Manager o utilizzare l'API di gestione tenant, gli utenti devono appartenere a un gruppo che dispone di almeno un'autorizzazione. Tutti gli utenti che possono accedere possono eseguire le seguenti operazioni:

* Visualizza la dashboard
* Modificare la propria password (per gli utenti locali)


Per tutte le autorizzazioni, l'impostazione della modalità di accesso del gruppo determina se gli utenti possono modificare le impostazioni ed eseguire operazioni o se possono visualizzare solo le relative impostazioni e funzionalità.


NOTE: Se un utente appartiene a più gruppi e un gruppo è impostato su sola lettura, l'utente avrà accesso in sola lettura a tutte le impostazioni e funzioni selezionate.

È possibile assegnare a un gruppo le seguenti autorizzazioni. Tenere presente che i tenant S3 e Swift dispongono di permessi di gruppo diversi.

[cols="1a,3a"]
|===
| Permesso | Descrizione 


 a| 
Accesso root
 a| 
Fornisce l'accesso completo al tenant Manager e all'API di gestione del tenant.

*Nota:* gli utenti Swift devono disporre dell'autorizzazione di accesso root per accedere all'account tenant.



 a| 
Amministratore
 a| 
Solo tenant Swift. Fornisce l'accesso completo ai container e agli oggetti Swift per questo account tenant

*Nota:* gli utenti di Swift devono disporre dell'autorizzazione di amministratore di Swift per eseguire qualsiasi operazione con l'API DI Swift REST.



 a| 
Gestisci le tue credenziali S3
 a| 
Consente agli utenti di creare e rimuovere le proprie chiavi di accesso S3. Gli utenti che non dispongono di questa autorizzazione non visualizzano l'opzione di menu *STORAGE (S3)* > *My S3 access keys*.



 a| 
Gestire tutti i bucket
 a| 
* S3 tenant: Consente agli utenti di utilizzare tenant Manager e l'API di gestione tenant per creare ed eliminare i bucket S3 e per gestire le impostazioni di tutti i bucket S3 nell'account tenant, indipendentemente dalle policy di gruppo o bucket S3.
+
Gli utenti che non dispongono di questa autorizzazione non visualizzano l'opzione di menu *Bucket*.

* Tenant Swift: Consente agli utenti Swift di controllare il livello di coerenza per i container Swift utilizzando l'API di gestione tenant.


*Nota:* è possibile assegnare l'autorizzazione Gestisci tutti i bucket solo ai gruppi Swift dall'API di gestione tenant. Non puoi assegnare questa autorizzazione ai gruppi Swift utilizzando il tenant Manager.



 a| 
Gestire gli endpoint
 a| 
Consente agli utenti di utilizzare il gestore tenant o l'API di gestione tenant per creare o modificare gli endpoint del servizio della piattaforma, che vengono utilizzati come destinazione per i servizi della piattaforma StorageGRID.

Gli utenti che non dispongono di questa autorizzazione non visualizzano l'opzione di menu *Platform Services Endpoint*.



 a| 
Gestire gli oggetti con la console S3
 a| 
Se combinato con l'autorizzazione Manage All bucket (Gestisci tutti i bucket), consente agli utenti di accedere alla console S3 sperimentale dalla pagina Bucket. Gli utenti che dispongono di questa autorizzazione ma che non dispongono dell'autorizzazione Manage All bucket possono comunque accedere direttamente alla console Experimental S3.

|===