---
permalink: tenant/tenant-management-api-versioning.html 
sidebar: sidebar 
keywords: tenant management api version 
summary: 'L"API di gestione tenant utilizza il controllo delle versioni per supportare aggiornamenti senza interruzioni.' 
---
= Versione dell'API di gestione tenant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'API di gestione tenant utilizza il controllo delle versioni per supportare aggiornamenti senza interruzioni.

Ad esempio, questo URL di richiesta specifica la versione 3 dell'API.

`https://_hostname_or_ip_address_/api/v3/authorize`

La versione principale dell'API di gestione tenant viene bloccata quando vengono apportate modifiche _non compatibili_ con le versioni precedenti. La versione minore dell'API di gestione tenant viene modificata quando vengono apportate modifiche che _sono compatibili_ con le versioni precedenti. Le modifiche compatibili includono l'aggiunta di nuovi endpoint o di nuove proprietà. Nell'esempio seguente viene illustrato il modo in cui la versione dell'API viene modificata in base al tipo di modifiche apportate.

[cols="2a,1a,1a"]
|===
| Tipo di modifica all'API | Versione precedente | Nuova versione 


 a| 
Compatibile con le versioni precedenti
 a| 
2.1
 a| 
2.2



 a| 
Non compatibile con versioni precedenti
 a| 
2.1
 a| 
3.0

|===
Quando il software StorageGRID viene installato per la prima volta, viene attivata solo la versione più recente dell'API di gestione del tenant. Tuttavia, quando StorageGRID viene aggiornato a una nuova release di funzionalità, si continua ad avere accesso alla versione API precedente per almeno una release di funzionalità StorageGRID.

Le richieste obsolete vengono contrassegnate come obsolete nei seguenti modi:

* L'intestazione della risposta è "Deprecated: True"
* Il corpo di risposta JSON include "deprecato": Vero




== Determinare quali versioni API sono supportate nella release corrente

Utilizzare la seguente richiesta API per restituire un elenco delle versioni principali dell'API supportate:

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== Specificare la versione API per la richiesta

È possibile specificare la versione dell'API utilizzando un parametro path (`/api/v3`) o un'intestazione (`Api-Version: 3`). Se si forniscono entrambi i valori, il valore dell'intestazione sovrascrive il valore del percorso.

`curl \https://<IP-Address>/api/v3/grid/accounts`

`curl -H "Api-Version: 3" \https://<IP-Address>/api/grid/accounts`
