---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to plan before installation 
summary: Prima di implementare i nodi grid e configurare la griglia StorageGRID, è necessario conoscere i passaggi e i requisiti per completare la procedura. 
---
= Prima dell'installazione (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di implementare i nodi grid e configurare la griglia StorageGRID, è necessario conoscere i passaggi e i requisiti per completare la procedura.

Le procedure di implementazione e configurazione di StorageGRID presuppongono una certa familiarità con l'architettura e le funzionalità operative del sistema StorageGRID.

È possibile implementare uno o più siti contemporaneamente; tuttavia, tutti i siti devono soddisfare il requisito minimo di avere almeno tre nodi di storage.

Prima di avviare la procedura di implementazione del nodo e di configurazione della griglia, è necessario:

* Pianificare l'implementazione di StorageGRID.
* Installazione, connessione e configurazione di tutto l'hardware richiesto, incluse eventuali appliance StorageGRID, in base alle specifiche.
+

IMPORTANT: Se l'installazione di StorageGRID non utilizza nodi di storage (hardware) dell'appliance StorageGRID, è necessario utilizzare lo storage RAID hardware con cache di scrittura supportata dalla batteria (BBWC). StorageGRID non supporta l'utilizzo di reti VSAN (Virtual Storage Area Network), RAID software o nessuna protezione RAID.

+

NOTE: Le istruzioni di installazione e integrazione specifiche dell'hardware non sono incluse nella procedura di installazione di StorageGRID. Per informazioni su come installare le appliance StorageGRID, vedere link:../installconfig/index.html["Installare l'hardware dell'appliance"].

* Comprendere link:../network/index.html["opzioni di rete disponibili e modalità di implementazione di ciascuna opzione di rete sui nodi di rete"].
* Raccogliere tutte le informazioni di rete in anticipo. A meno che non si utilizzi DHCP, raccogliere gli indirizzi IP da assegnare a ciascun nodo della griglia e gli indirizzi IP dei server DNS e NTP che verranno utilizzati.
* Decidere quali strumenti di implementazione e configurazione si desidera utilizzare.

