---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: browser inactivity timeout, inactive users 
summary: È possibile controllare se gli utenti di Grid Manager e Tenant Manager vengono disconnessi se rimangono inattivi per più di un certo periodo di tempo. 
---
= Modificare il timeout di inattività del browser
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile controllare se gli utenti di Grid Manager e Tenant Manager vengono disconnessi se rimangono inattivi per più di un certo periodo di tempo.

.Prima di iniziare
* Hai effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone dell'autorizzazione di accesso root.


.A proposito di questa attività
Il timeout di inattività del browser viene impostato per impostazione predefinita su 15 minuti. Se il browser di un utente non è attivo per questo periodo di tempo, l'utente viene disconnesso.

Se necessario, è possibile aumentare o ridurre il periodo di timeout impostando l'opzione *Disconnetti utenti inattivi dopo*.

Il timeout di inattività del browser è controllato anche da:

* Un timer StorageGRID separato, non configurabile, incluso per la sicurezza del sistema. Per impostazione predefinita, ogni token di autenticazione dell'utente scade 16 ore dopo l'accesso. Alla scadenza dell'autenticazione di un utente, l'utente viene automaticamente disconnesso, anche se il timeout di inattività del browser è disattivato o non è stato raggiunto il valore di timeout del browser. Per rinnovare il token, l'utente deve effettuare nuovamente l'accesso.
* Impostazioni di timeout per il provider di identità, presupponendo che SSO (Single Sign-on) sia abilitato per StorageGRID.
+
Se SSO è attivato e il browser dell'utente si disinserisce, l'utente deve immettere nuovamente le proprie credenziali SSO per accedere nuovamente a StorageGRID. Vedere link:configuring-sso.html["Configurare il single sign-on"].



.Fasi
. Selezionare *CONFIGURATION* > *Security* > *Security settings*.
. Selezionare la scheda *Timeout inattività browser*.
. Nel campo *Disconnetti utenti inattivi dopo*, specificare un periodo di timeout del browser compreso tra 60 secondi e 7 giorni.
+
È possibile specificare il periodo di timeout del browser in secondi, minuti, ore o giorni.

. Selezionare *Salva*. Se un browser rimane inattivo per il periodo di tempo specificato, l'utente viene disconnesso da Grid Manager o da Tenant Manager.
+
La nuova impostazione non influisce sugli utenti attualmente registrati. Gli utenti devono effettuare nuovamente l'accesso o aggiornare il browser per rendere effettiva la nuova impostazione di timeout.


