---
permalink: admin/grid-management-api-versioning.html 
sidebar: sidebar 
keywords: grid management api, api versioning 
summary: 'L"API Grid Management utilizza il controllo delle versioni per supportare aggiornamenti senza interruzioni.' 
---
= Versione dell'API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'API Grid Management utilizza il controllo delle versioni per supportare aggiornamenti senza interruzioni.

Ad esempio, questo URL di richiesta specifica la versione 3 dell'API.

`https://_hostname_or_ip_address_/api/v3/authorize`

La versione principale dell'API di gestione tenant viene bloccata quando vengono apportate modifiche *_non compatibili_* con le versioni precedenti. La versione minore dell'API di gestione tenant viene ridotta quando vengono apportate modifiche che *_sono compatibili_* con le versioni precedenti. Le modifiche compatibili includono l'aggiunta di nuovi endpoint o di nuove proprietà. Nell'esempio seguente viene illustrato il modo in cui la versione dell'API viene modificata in base al tipo di modifiche apportate.

[cols="1a,1a,1a"]
|===
| Tipo di modifica all'API | Versione precedente | Nuova versione 


 a| 
Compatibile con le versioni precedenti
 a| 
2.1
 a| 
2.2



 a| 
Non compatibile con versioni precedenti
 a| 
2.1
 a| 
3.0

|===
Quando si installa il software StorageGRID per la prima volta, viene attivata solo la versione più recente dell'API di gestione griglia. Tuttavia, quando si esegue l'aggiornamento a una nuova release di funzionalità di StorageGRID, si continua ad avere accesso alla versione precedente dell'API per almeno una release di funzionalità di StorageGRID.


NOTE: È possibile utilizzare l'API Grid Management per configurare le versioni supportate. Per ulteriori informazioni, consultare la sezione "`config`" della documentazione dell'API Swagger. Disattivare il supporto per la versione precedente dopo aver aggiornato tutti i client API Grid Management per utilizzare la versione più recente.

Le richieste obsolete vengono contrassegnate come obsolete nei seguenti modi:

* L'intestazione della risposta è "Deprecated: True"
* Il corpo di risposta JSON include "deprecato": Vero
* Viene aggiunto un avviso obsoleto a nms.log. Ad esempio:
+
[listing]
----
Received call to deprecated v1 API at POST "/api/v1/authorize"
----




== Determinare quali versioni API sono supportate nella release corrente

Utilizzare la seguente richiesta API per restituire un elenco delle versioni principali dell'API supportate:

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== Specificare una versione API per una richiesta

È possibile specificare la versione dell'API utilizzando un parametro path (`/api/v3`) o un'intestazione (`Api-Version: 3`). Se si forniscono entrambi i valori, il valore dell'intestazione sovrascrive il valore del percorso.

[listing]
----
curl https://[IP-Address]/api/v3/grid/accounts

curl -H "Api-Version: 3" https://[IP-Address]/api/grid/accounts
----