---
permalink: admin/kms-removing.html 
sidebar: sidebar 
keywords: remove kms, remove key management server 
summary: In alcuni casi, potrebbe essere necessario rimuovere un server di gestione delle chiavi. Ad esempio, è possibile rimuovere un KMS specifico del sito se il sito è stato decommissionato. 
---
= Rimozione di un server di gestione delle chiavi (KMS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In alcuni casi, potrebbe essere necessario rimuovere un server di gestione delle chiavi. Ad esempio, è possibile rimuovere un KMS specifico del sito se il sito è stato decommissionato.

.Prima di iniziare
* Hai esaminato il link:kms-considerations-and-requirements.html["considerazioni e requisiti per l'utilizzo di un server di gestione delle chiavi"].
* Hai effettuato l'accesso a Grid Manager utilizzando un link:../admin/web-browser-requirements.html["browser web supportato"].
* Si dispone dell'autorizzazione di accesso root.


.A proposito di questa attività
È possibile rimuovere un KMS nei seguenti casi:

* È possibile rimuovere un KMS specifico del sito se il sito è stato decommissionato o se il sito non include nodi appliance con crittografia del nodo attivata.
* È possibile rimuovere il KMS predefinito se esiste già un KMS specifico del sito per ogni sito che ha nodi appliance con crittografia del nodo attivata.


.Fasi
. Selezionare *CONFIGURATION* > *Security* > *Key management server*.
+
Viene visualizzata la pagina Key management server (Server di gestione delle chiavi) che mostra tutti i server di gestione delle chiavi configurati.

. Selezionare il KMS che si desidera rimuovere e selezionare *azioni* > *Rimuovi*.
+
Puoi anche rimuovere un KMS selezionando il nome del KMS nella tabella e selezionando *Remove* dalla pagina dei dettagli del KMS.

. Verificare che quanto segue sia vero:
+
** Si sta rimuovendo un KMS specifico del sito per un sito che non dispone di un nodo appliance con crittografia del nodo attivata.
** Si sta rimuovendo il KMS predefinito, ma esiste già un KMS specifico del sito per ogni sito con crittografia del nodo.


. Selezionare *Sì*.
+
La configurazione KMS viene rimossa.


