---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: I nodi di amministrazione forniscono servizi di gestione quali configurazione, monitoraggio e registrazione del sistema. Ogni grid deve avere un nodo di amministrazione primario e può avere un numero qualsiasi di nodi di amministrazione non primari per la ridondanza. 
---
= Che cos'è un nodo amministratore?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nodi di amministrazione forniscono servizi di gestione quali configurazione, monitoraggio e registrazione del sistema. Ogni grid deve avere un nodo di amministrazione primario e può avere un numero qualsiasi di nodi di amministrazione non primari per la ridondanza.

Quando si accede a Grid Manager o al tenant Manager, si sta effettuando la connessione a un nodo amministratore. È possibile connettersi a qualsiasi nodo amministratore e ciascun nodo amministratore visualizza una vista simile del sistema StorageGRID. Tuttavia, le procedure di manutenzione devono essere eseguite utilizzando il nodo di amministrazione primario.

I nodi di amministrazione possono anche essere utilizzati per bilanciare il carico del traffico dei client S3 e Swift.



== Qual è il mittente preferito

Se l'implementazione di StorageGRID include più nodi di amministrazione, il nodo di amministrazione primario è il mittente preferito per le notifiche di avviso, i messaggi AutoSupport, le trap SNMP e le informazioni e le notifiche di allarme legacy.

Nelle normali operazioni di sistema, solo il mittente preferito invia le notifiche. Tuttavia, tutti gli altri nodi Admin monitorano il mittente preferito. Se viene rilevato un problema, gli altri nodi Admin fungono da _mittenti di standby_.

In questi casi potrebbero essere inviate più notifiche:

* Se i nodi Admin diventano "islanded" l'uno dall'altro, sia il mittente preferito che i mittenti in standby tenteranno di inviare notifiche e potrebbero essere ricevute più copie delle notifiche.
* Se il mittente in standby rileva problemi con il mittente preferito e inizia a inviare notifiche, il mittente preferito potrebbe riacquistare la capacità di inviare notifiche. In questo caso, potrebbero essere inviate notifiche duplicate. Il mittente in standby interrompe l'invio di notifiche quando non rileva più errori sul mittente preferito.
+

NOTE: Quando si testano i messaggi AutoSupport, tutti i nodi di amministrazione inviano l'email di prova. Quando si verificano le notifiche di avviso, è necessario accedere a ogni nodo amministratore per verificare la connettività.





== Servizi primari per nodi di amministrazione

La tabella seguente mostra i servizi primari per i nodi di amministrazione; tuttavia, questa tabella non elenca tutti i servizi dei nodi.

[cols="1a,2a"]
|===
| Servizio | Funzione dei tasti 


 a| 
Sistema di gestione dell'audit (AMS)
 a| 
Tiene traccia dell'attività e degli eventi del sistema.



 a| 
Nodo di gestione della configurazione (CMN)
 a| 
Gestisce la configurazione a livello di sistema. Solo nodo amministratore primario.



 a| 
Management Application Program Interface (Mgmt-api)
 a| 
Elabora le richieste provenienti dall'API Grid Management e dall'API Tenant Management.



 a| 
Alta disponibilità
 a| 
Gestisce gli indirizzi IP virtuali ad alta disponibilità per gruppi di nodi di amministrazione e nodi gateway.

*Nota:* questo servizio si trova anche sui nodi gateway.



 a| 
Bilanciamento del carico
 a| 
Fornisce il bilanciamento del carico del traffico S3 e Swift dai client ai nodi di storage.

*Nota:* questo servizio si trova anche sui nodi gateway.



 a| 
NMS (Network Management System)
 a| 
Fornisce funzionalità per Grid Manager.



 a| 
Prometheus
 a| 
Raccoglie e memorizza le metriche delle serie temporali dai servizi su tutti i nodi.



 a| 
Server Status Monitor (SSM)
 a| 
Monitora il sistema operativo e l'hardware sottostante.

|===