---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords: s3 rest api support changes 
summary: 'Si consiglia di essere a conoscenza delle modifiche apportate al supporto del sistema StorageGRID per l"API REST S3.' 
---
= Modifiche al supporto delle API REST S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario essere consapevoli delle modifiche apportate al supporto del sistema StorageGRID per l'API REST S3.

[cols="1a,4a"]
|===
| Rilasciare | Commenti 


 a| 
11.7
 a| 
* Aggiunto supporto per l'utilizzo della modalità DI GOVERNANCE con S3 Object Lock.
* Aggiunto supporto per StorageGRID specifico `x-ntap-sg-cgr-replication-status` Intestazione di risposta per le richieste DI oggetti GET e HEAD. Questa intestazione fornisce lo stato di replica di un oggetto per la replica cross-grid.
* Le richieste SelectObjectContent ora supportano gli oggetti Parquet.




 a| 
11.6
 a| 
* Aggiunto supporto per l'utilizzo di `partNumber` Parametro di richiesta in GET object e HEAD object requests.
* Aggiunto supporto per una modalità di conservazione predefinita e un periodo di conservazione predefinito a livello di bucket per S3 Object Lock.
* Aggiunto supporto per `s3:object-lock-remaining-retention-days` policy condition key (chiave condizione policy) per impostare l'intervallo di periodi di conservazione consentiti per gli oggetti.
* Modifica della dimensione massima _consigliata_ per un'operazione di singolo oggetto PUT in 5 GiB (5,368,709,120 byte). Se si dispone di oggetti di dimensioni superiori a 5 GiB, utilizzare invece il caricamento multiparte.




 a| 
11.5
 a| 
* Aggiunto supporto per la gestione della crittografia bucket.
* Aggiunto supporto per S3 Object Lock e richieste legacy di Compliance obsolete.
* Aggiunto il supporto per l'utilizzo DELL'ELIMINAZIONE di più oggetti nei bucket con versione.
* Il `Content-MD5` l'intestazione della richiesta è ora supportata correttamente.




 a| 
11.4
 a| 
* Aggiunto supporto per L'ELIMINAZIONE di tag bucket, L'AGGIUNTA DI tag bucket E L'AGGIUNTA di tag bucket. I tag di allocazione dei costi non sono supportati.
* Per i bucket creati in StorageGRID 11.4, non è più necessario limitare i nomi delle chiavi degli oggetti per soddisfare le Best practice di performance.
* Aggiunto supporto per le notifiche bucket su `s3:ObjectRestore:Post` tipo di evento.
* I limiti di dimensione AWS per le parti multicpart vengono ora applicati. Ogni parte di un caricamento multiparte deve essere compresa tra 5 MiB e 5 GiB. L'ultima parte può essere inferiore a 5 MiB.
* Aggiunto supporto per TLS 1.3




 a| 
11.3
 a| 
* Aggiunto supporto per la crittografia lato server dei dati a oggetti con chiavi fornite dal cliente (SSE-C).
* Supporto aggiunto per LE operazioni DI eliminazione, GET e PUT del ciclo di vita del bucket (solo azione di scadenza) e per `x-amz-expiration` intestazione della risposta.
* Aggiornamento DI PUT object, PUT object - Copy e Multippart Upload per descrivere l'impatto delle regole ILM che utilizzano il posizionamento sincrono durante l'acquisizione.
* Le crittografia TLS 1.1 non sono più supportate.




 a| 
11.2
 a| 
Aggiunto supporto per il ripristino POST-oggetto da utilizzare con i Cloud Storage Pools. Aggiunto supporto per l'utilizzo della sintassi AWS per ARN, chiavi di condizione dei criteri e variabili dei criteri in policy di gruppo e bucket. Le policy di gruppo e bucket esistenti che utilizzano la sintassi StorageGRID continueranno a essere supportate.

*Nota:* gli utilizzi di ARN/URN in altre configurazioni JSON/XML, inclusi quelli utilizzati nelle funzionalità personalizzate di StorageGRID, non sono cambiati.



 a| 
11.1
 a| 
Aggiunto supporto per la condivisione delle risorse tra origini (CORS), HTTP per connessioni client S3 ai nodi di rete e impostazioni di conformità sui bucket.



 a| 
11.0
 a| 
Supporto aggiunto per la configurazione dei servizi della piattaforma (replica CloudMirror, notifiche e integrazione della ricerca Elasticsearch) per i bucket. Inoltre, è stato aggiunto il supporto per i vincoli di posizione per il tag degli oggetti per i bucket e l'impostazione di controllo della coerenza disponibile.



 a| 
10.4
 a| 
Aggiunto supporto per le modifiche di scansione ILM alle versioni, agli aggiornamenti delle pagine dei nomi di dominio degli endpoint, alle condizioni e alle variabili nei criteri, agli esempi di policy e all'autorizzazione PutOverwriteObject.



 a| 
10.3
 a| 
Aggiunto supporto per il controllo delle versioni.



 a| 
10.2
 a| 
Aggiunto supporto per policy di accesso di gruppo e bucket e per copia multiparte (carica parte - Copia).



 a| 
10.1
 a| 
Aggiunto supporto per upload multiparte, richieste virtuali in stile host e autenticazione v4.



 a| 
10.0
 a| 
Supporto iniziale dell'API REST S3 da parte del sistema StorageGRID. La versione attualmente supportata del _riferimento API del servizio di storage semplice_ è 2006-03-01.

|===