---
permalink: s3/operations-for-multipart-uploads.html 
sidebar: sidebar 
keywords: operations, multipart uploads, uploads, rest API 
summary: Questa sezione descrive come StorageGRID supporta le operazioni per gli upload di più parti. 
---
= Operazioni per caricamenti multiparte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questa sezione descrive come StorageGRID supporta le operazioni per gli upload di più parti.

Le seguenti condizioni e note si applicano a tutte le operazioni di caricamento multiparte:

* Non superare i 1,000 caricamenti simultanei di più parti in un singolo bucket, perché i risultati delle query di upload di List Multipart per quel bucket potrebbero restituire risultati incompleti.
* StorageGRID applica i limiti di dimensione AWS per le parti multicpart. I client S3 devono seguire queste linee guida:
+
** Ciascuna parte di un caricamento multiparte deve essere compresa tra 5 MiB (5,242,880 byte) e 5 GiB (5,368,709,120 byte).
** L'ultima parte può essere inferiore a 5 MiB (5,242,880 byte).
** In generale, le dimensioni delle parti devono essere il più grandi possibile. Ad esempio, utilizzare le dimensioni delle parti di 5 GiB per un oggetto 100 GiB. Poiché ogni parte è considerata un oggetto unico, l'utilizzo di parti di grandi dimensioni riduce l'overhead dei metadati StorageGRID.
** Per gli oggetti di dimensioni inferiori a 5 GiB, prendere in considerazione l'utilizzo di un caricamento non multiparte.


* ILM viene valutato per ogni parte di un oggetto multiparte durante l'acquisizione e per l'oggetto nel suo complesso al termine del caricamento multiparte, se la regola ILM utilizza il comportamento di acquisizione bilanciato o rigoroso. Devi essere consapevole di come questo influisca sul posizionamento di oggetti e parti:
+
** Se ILM cambia mentre è in corso un caricamento S3 multiparte, quando il caricamento multiparte completa alcune parti dell'oggetto potrebbero non soddisfare i requisiti ILM correnti. Tutte le parti non posizionate correttamente vengono messe in coda per la rivalutazione ILM e spostate nella posizione corretta in un secondo momento.
** Quando si valuta ILM per una parte, StorageGRID filtra sulla dimensione della parte, non sulla dimensione dell'oggetto. Ciò significa che parti di un oggetto possono essere memorizzate in posizioni che non soddisfano i requisiti ILM per l'oggetto nel suo complesso. Ad esempio, se una regola specifica che tutti gli oggetti da 10 GB o superiori sono memorizzati in DC1 mentre tutti gli oggetti più piccoli sono memorizzati in DC2, ogni parte da 1 GB di un caricamento multiparte da 10 parti viene memorizzata in DC2. Quando ILM viene valutato per l'oggetto nel suo complesso, tutte le parti dell'oggetto vengono spostate in DC1.


* Tutte le operazioni di caricamento multiparte supportano i controlli di coerenza StorageGRID.
* Se necessario, è possibile utilizzare la crittografia lato server con upload multiparte. Per utilizzare SSE (crittografia lato server con chiavi gestite da StorageGRID), è necessario includere `x-amz-server-side-encryption` Intestazione della richiesta solo nella richiesta di avvio caricamento multiparte. Per utilizzare SSE-C (crittografia lato server con chiavi fornite dal cliente), specificare le stesse tre intestazioni di richiesta della chiave di crittografia nella richiesta Initiate Multipart Upload (Avvia caricamento multiparte) e in ogni richiesta successiva di caricamento parte.


[cols="2a,3a"]
|===
| Operazione | Implementazione 


 a| 
Elenca caricamenti multiparte
 a| 
Vedere link:list-multipart-uploads.html["Elenca caricamenti multiparte"]



 a| 
Avvia caricamento multiparte
 a| 
Vedere link:initiate-multipart-upload.html["Avvia caricamento multiparte"]



 a| 
Carica parte
 a| 
Vedere link:upload-part.html["Carica parte"]



 a| 
Carica parte - Copia
 a| 
Vedere link:upload-part-copy.html["Carica parte - Copia"]



 a| 
Caricamento multiparte completo
 a| 
Vedere link:complete-multipart-upload.html["Caricamento multiparte completo"]



 a| 
Interrompi caricamento multiparte
 a| 
Implementato con tutti i comportamenti REST API di Amazon S3. Soggetto a modifiche senza preavviso.



 a| 
Elencare le parti
 a| 
Implementato con tutti i comportamenti REST API di Amazon S3. Soggetto a modifiche senza preavviso.

|===
.Informazioni correlate
* link:consistency-controls.html["Controlli di coerenza"]
* link:using-server-side-encryption.html["Utilizzare la crittografia lato server"]

