---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: 'È possibile utilizzare la richiesta di ripristino dell"oggetto POST S3 per ripristinare un oggetto memorizzato in un Cloud Storage Pool.' 
---
= RIPRISTINO POST-oggetto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la richiesta di ripristino dell'oggetto POST S3 per ripristinare un oggetto memorizzato in un Cloud Storage Pool.



== Tipo di richiesta supportato

StorageGRID supporta solo le richieste DI ripristino degli oggetti POST per ripristinare un oggetto. Non supporta `SELECT` tipo di ripristino. Selezionare Requests Return `XNotImplemented`.



== Versione

Facoltativamente, specificare `versionId` per ripristinare una versione specifica di un oggetto in un bucket con versione. Se non si specifica `versionId`, viene ripristinata la versione più recente dell'oggetto



== Comportamento del ripristino degli oggetti POST sugli oggetti del Cloud Storage Pool

Se un oggetto è stato memorizzato in un Cloud Storage Pool (vedere le istruzioni per la gestione degli oggetti con gestione del ciclo di vita delle informazioni), una richiesta DI ripristino DELL'oggetto POST ha il seguente comportamento, in base allo stato dell'oggetto. Per ulteriori informazioni, consulta "`HEAD Object`".


NOTE: Se un oggetto viene memorizzato in un Cloud Storage Pool e una o più copie dell'oggetto sono presenti anche nella griglia, non è necessario ripristinare l'oggetto emettendo una richiesta DI ripristino POST-oggetto. Invece, la copia locale può essere recuperata direttamente, utilizzando una richiesta DI oggetto GET.

[cols="1a,2a"]
|===
| Stato dell'oggetto | Comportamento del ripristino degli oggetti POST 


 a| 
Oggetto acquisito in StorageGRID ma non ancora valutato da ILM, o oggetto non presente in un pool di storage cloud
 a| 
`403 Forbidden`, `InvalidObjectState`



 a| 
Oggetto nel Cloud Storage Pool ma non ancora passato a uno stato non recuperabile
 a| 
`200 OK` Non vengono apportate modifiche.

*Nota*: Prima che un oggetto sia stato spostato in uno stato non recuperabile, non è possibile modificarne lo stato `expiry-date`.



 a| 
Oggetto sottoposto a transizione in uno stato non recuperabile
 a| 
`202 Accepted` Ripristina una copia recuperabile dell'oggetto nel Cloud Storage Pool per il numero di giorni specificato nel corpo della richiesta. Al termine di questo periodo, l'oggetto viene riportato in uno stato non recuperabile.

In alternativa, utilizzare `Tier` elemento request per determinare il tempo necessario per il completamento del processo di ripristino (`Expedited`, `Standard`, o. `Bulk`). Se non si specifica `Tier`, il `Standard` viene utilizzato il tier.

*Importante*: Se un oggetto è stato spostato in S3 Glacier Deep Archive o il Cloud Storage Pool utilizza lo storage Azure Blob, non è possibile ripristinarlo utilizzando `Expedited` tier. Viene visualizzato il seguente errore `403 Forbidden`, `InvalidTier`: `Retrieval option is not supported by this storage class`.



 a| 
Oggetto in fase di ripristino da uno stato non recuperabile
 a| 
`409 Conflict`, `RestoreAlreadyInProgress`



 a| 
Oggetto completamente ripristinato nel Cloud Storage Pool
 a| 
`200 OK`

*Nota:* se un oggetto è stato ripristinato a uno stato recuperabile, è possibile modificarne lo stato `expiry-date` Inviando nuovamente la richiesta DI ripristino dell'oggetto POST con un nuovo valore per `Days`. La data di ripristino viene aggiornata in relazione all'ora della richiesta.

|===
.Informazioni correlate
link:../ilm/index.html["Gestire gli oggetti con ILM"]

link:head-object.html["Oggetto TESTA"]

link:s3-operations-tracked-in-audit-logs.html["Operazioni S3 monitorate nei registri di audit"]
