---
permalink: maintain/index.html 
sidebar: sidebar 
keywords: maintain overview, maintenance overview, about maintain, about maintenance 
summary: Attenersi alle seguenti istruzioni per la manutenzione del sistema StorageGRID e per il ripristino in caso di guasti. 
---
= Recovery and maintain (Ripristino e manutenzione): Panoramica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Attenersi alle seguenti istruzioni per la manutenzione del sistema StorageGRID e per il ripristino in caso di guasti.



== A proposito di queste istruzioni

Queste istruzioni descrivono come applicare una correzione rapida del software, ripristinare i nodi della griglia, ripristinare un sito guasto, decommissionare i nodi della griglia o un intero sito, eseguire la manutenzione della rete, eseguire le procedure di manutenzione del middleware e a livello di host ed eseguire le procedure dei nodi della griglia.


NOTE: In queste istruzioni, "`Linux`" si riferisce a una distribuzione Red Hat® Enterprise Linux®, Ubuntu®, CentOS o Debian®. Utilizzare https://imt.netapp.com/matrix/#welcome["Tool di matrice di interoperabilità NetApp"^] per ottenere un elenco delle versioni supportate.



== Prima di iniziare

* Hai una vasta conoscenza del sistema StorageGRID.
* Hai esaminato la topologia del sistema StorageGRID e hai compreso la configurazione della griglia.
* Si comprende che è necessario seguire tutte le istruzioni con precisione e prestare attenzione a tutte le avvertenze.
* Comprendete che le procedure di manutenzione non descritte non sono supportate o richiedono un intervento di assistenza.




== Procedure di manutenzione per le appliance

Per le procedure relative all'hardware, consultare le istruzioni di manutenzione dell'appliance StorageGRID.

* link:../sg6100/index.html["Manutenzione dell'appliance SGF6112"]
* link:../sg100-1000/index.html["Manutenzione delle appliance SG100 e SG1000"]
* link:../sg6000/index.html["Manutenzione dell'appliance SG6000"]
* link:../sg5700/index.html["Manutenzione dell'appliance SG5700"]

