---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: Se si prevede di decommissionare un nodo di storage, è necessario rivedere la policy ILM del sistema StorageGRID prima di avviare il processo di decommissionamento. 
---
= Esaminare i criteri ILM e la configurazione dello storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si prevede di decommissionare un nodo di storage, è necessario rivedere la policy ILM del sistema StorageGRID prima di avviare il processo di decommissionamento.

Durante lo smantellamento, tutti i dati degli oggetti vengono migrati dal nodo di storage decommissionato ad altri nodi di storage.


NOTE: La policy ILM di cui disponi _durante_ la decommissionazione sarà quella utilizzata _dopo_ la decommissionazione. È necessario assicurarsi che questa policy soddisfi i requisiti dei dati prima di iniziare la decommissionazione e dopo il completamento della decommissionazione.

È necessario rivedere le regole nel criterio ILM attivo per assicurarsi che il sistema StorageGRID continui a disporre di capacità sufficiente del tipo corretto e nelle posizioni corrette per consentire la disattivazione di un nodo di storage.

Considerare quanto segue:

* I servizi di valutazione ILM potranno copiare i dati degli oggetti in modo che le regole ILM siano soddisfatte?
* Cosa succede se un sito diventa temporaneamente non disponibile mentre è in corso la disattivazione? È possibile eseguire copie aggiuntive in una posizione alternativa?
* In che modo il processo di disattivazione influirà sulla distribuzione finale dei contenuti? Come descritto in link:consolidating-storage-nodes.html["Consolidare i nodi di storage"], È necessario aggiungere nuovi nodi di storage prima di decommissionare quelli vecchi. Se si aggiunge un nodo di storage sostitutivo più grande dopo la disattivazione di un nodo di storage più piccolo, i vecchi nodi di storage potrebbero essere vicini alla capacità e il nuovo nodo di storage potrebbe non avere quasi alcun contenuto. La maggior parte delle operazioni di scrittura per i nuovi dati a oggetti verrebbe quindi indirizzata al nuovo nodo di storage, riducendo l'efficienza complessiva delle operazioni di sistema.
* Il sistema includerà sempre un numero sufficiente di nodi di storage per soddisfare la policy ILM attiva?
+

NOTE: Una policy ILM che non può essere soddisfatta porterà a backlog e allarmi e può interrompere il funzionamento del sistema StorageGRID.



Verificare che la topologia proposta risultante dal processo di decommissionamento soddisfi la policy ILM valutando i fattori elencati nella tabella.

[cols="1a,2a"]
|===
| Area da valutare | Note 


 a| 
Capacità disponibile
 a| 
La capacità dello storage è sufficiente per ospitare tutti i dati degli oggetti memorizzati nel sistema StorageGRID, Incluse le copie permanenti dei dati dell'oggetto attualmente memorizzati nel nodo di storage da smantellare?la capacità sarà sufficiente per gestire la crescita prevista dei dati dell'oggetto memorizzato per un intervallo di tempo ragionevole dopo il completamento della disattivazione?



 a| 
Ubicazione dello storage
 a| 
Se nel sistema StorageGRID rimane una capacità sufficiente, la capacità è nelle posizioni giuste per soddisfare le regole di business del sistema StorageGRID?



 a| 
Tipo di storage
 a| 
Sarà disponibile uno storage sufficiente del tipo appropriato dopo il completamento dello smantellamento? Ad esempio, le regole ILM potrebbero imporre che il contenuto venga spostato da un tipo di storage all'altro in base all'età del contenuto. In tal caso, è necessario assicurarsi che nella configurazione finale del sistema StorageGRID sia disponibile una quantità sufficiente di storage del tipo appropriato.

|===
.Informazioni correlate
link:../ilm/index.html["Gestire gli oggetti con ILM"]

link:../expand/index.html["Espandi il tuo grid"]
