---
permalink: expand/contacting-technical-support.html 
sidebar: sidebar 
keywords: contact technical support 
summary: 'Se durante il processo di espansione della griglia si verificano errori che non è possibile risolvere o se un"attività della griglia non riesce, contattare il supporto tecnico.' 
---
= Contattare il supporto tecnico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se durante il processo di espansione della griglia si verificano errori che non è possibile risolvere o se un'attività della griglia non riesce, contattare il supporto tecnico.

.A proposito di questa attività
Quando si contatta il supporto tecnico, è necessario fornire i file di registro necessari per la risoluzione degli errori riscontrati.

.Fasi
. Connettersi al nodo di espansione che ha riscontrato errori:
+
.. Immettere il seguente comando:``ssh -p 8022 admin@_grid_node_IP_``
+

NOTE: La porta 8022 è la porta SSH del sistema operativo di base, mentre la porta 22 è la porta SSH del motore dei container che esegue StorageGRID.

.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.

. A seconda della fase di installazione raggiunta, recuperare uno dei seguenti log disponibili nel nodo grid:
+
[cols="1a,2a"]
|===
| Piattaforma | Registri 


 a| 
VMware
 a| 
** `/var/log/daemon.log`
** `/var/log/storagegrid/daemon.log`
** `/var/log/storagegrid/nodes/<node-name>.log`




 a| 
Linux
 a| 
** `/var/log/storagegrid/daemon.log`
** `/etc/storagegrid/nodes/<node-name>.conf` (per ogni nodo guasto)
** `/var/log/storagegrid/nodes/<node-name>.log` (per ogni nodo guasto; potrebbe non esistere)


|===

