---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Un pool di storage è un raggruppamento logico di nodi di storage o nodi di archivio. 
---
= Che cos'è un pool di storage?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool di storage è un raggruppamento logico di nodi di storage o nodi di archivio.

Quando si installa StorageGRID, viene creato automaticamente un pool di storage per sito. È possibile configurare ulteriori pool di storage in base alle esigenze di storage.

[NOTE]
====
Il supporto per i nodi di archiviazione (sia per l'archiviazione nel cloud utilizzando l'API S3 che per l'archiviazione su nastro utilizzando il middleware TSM) è obsoleto e verrà rimosso in una release futura. Lo spostamento di oggetti da un nodo di archiviazione a un sistema storage di archiviazione esterno è stato sostituito da pool di storage cloud ILM, che offrono maggiori funzionalità.

Vedere link:../ilm/what-cloud-storage-pool-is.html["Utilizza i Cloud Storage Pools"].

====
I pool di storage hanno due attributi:

* *Storage grade*: Per i nodi di storage, le performance relative dello storage di backup.
* *Sito*: Il data center in cui verranno memorizzati gli oggetti.


I pool di storage vengono utilizzati nelle regole ILM per determinare dove sono memorizzati i dati degli oggetti e il tipo di storage utilizzato. Quando si configurano le regole ILM per la replica, si selezionano uno o più pool di storage che includono nodi di storage o nodi di archivio. Quando si creano profili di erasure coding, si seleziona un pool di storage che include i nodi di storage.
